### ISSUE TITLE
Run Scripts though mSLDev - Multiple issues. 

### ISSUE THREAD

**Issue by ghost** [solbu/Peace-and-Protection#14]
Might be interested in loading your script into [mSLDev](http://www.msldev.com/) (mIRC scripting IDE). Do note that the program is much stricter than mIRC is. 

One example of of issues it has found:

The following lines have `script(0)` that should be `$script(0)`
https://github.com/solbu/Peace-and-Protection/blob/master/script/first.mrc#L300
https://github.com/solbu/Peace-and-Protection/blob/master/script/first.mrc#L305
https://github.com/solbu/Peace-and-Protection/blob/master/script/first.mrc#L310
https://github.com/solbu/Peace-and-Protection/blob/master/script/first.mrc#L315
https://github.com/solbu/Peace-and-Protection/blob/master/script/first.mrc#L320
https://github.com/solbu/Peace-and-Protection/blob/master/script/first.mrc#L325

**Comment by craze** [comment]
Noting «that the program is much stricter than mIRC is.»
So the issue is with mSLDev and not PnP?

**Comment by ghost** [comment]
I guess I should of given an example: `alias testing { echo -ag $calc(1 + 1)) }` while it works in mIRC, mSLDev will report the extra `)` that should not be there. That is what I am referring too, as a script with some slight syntax issues might work, its still wrong.

**Comment by ghost** [comment]
Roaming/mIRC/script/window.mrc 545:40 block Ident: $window: Invalid property - Ident possess no such property
Roaming/mIRC/script/window.mrc 546:40 block Ident: $window: Invalid property - Ident possess no such property
Roaming/mIRC/script/window.mrc 547:40 block Ident: $window: Invalid property - Ident possess no such property
Roaming/mIRC/script/window.mrc 548:40 block Ident: $window: Invalid property - Ident possess no such property
Roaming/mIRC/script/window.mrc 549:40 block Ident: $window: Invalid property - Ident possess no such property
Roaming/mIRC/script/window.mrc 550:40 block Ident: $window: Invalid property - Ident possess no such property
Roaming/mIRC/script/window.mrc 551:40 block Ident: $window: Invalid property - Ident possess no such property
Roaming/mIRC/script/window.mrc 552:40 block Ident: $window: Invalid property - Ident possess no such property
Roaming/mIRC/script/window.mrc 553:40 block Ident: $window: Invalid property - Ident possess no such property
Roaming/mIRC/script/window.mrc 555:106 block Ident: $window: Invalid property - Ident possess no such property
Roaming/mIRC/script/window.mrc 555:168 block Ident: $window: Invalid property - Ident possess no such property
Roaming/mIRC/script/window.mrc 684:51 block Ident: $window: Invalid property - Ident possess no such property
Roaming/mIRC/script/window.mrc 687:51 block Ident: $window: Invalid property - Ident possess no such property

`$window($active).titlebar` 

Error: identifier $window posseses no such property: .titlebar

This might not be documented in mIRC's help file, but the property .titlebar does appear to return the same information as the property .title

Conclusion: code works, but undocumented property .titlebar might 'disappear' in the future. Update to .title at leisure or when it breaks.

**Comment by ghost** [comment]
Roaming/mIRC/script/script.mrc 523:48 block Ident: $ignore: Invalid property - Ident possess no such property

`.ignore -r $+ $iif($ignore(%num).network == $null,w) %who`

Error: $ignore does not posses property .network

In mIRC's help file only two properties are listed under $ignore: .type and .secs, however under alias /ignore the .network property is listed for the $ignore identifier.

Conclusion: code works fine in PnP. Issue is with mSLDev

**Comment by ghost** [comment]
Roaming/mIRC/script/first.mrc 300:92 block Illegal math operations in $calc()
Roaming/mIRC/script/first.mrc 305:86 block Illegal math operations in $calc()
Roaming/mIRC/script/first.mrc 310:84 block Illegal math operations in $calc()
Roaming/mIRC/script/first.mrc 315:80 block Illegal math operations in $calc()
Roaming/mIRC/script/first.mrc 320:92 block Illegal math operations in $calc()
Roaming/mIRC/script/first.mrc 325:86 block Illegal math operations in $calc()

`$calc(script(0) - 2)`

Error: 6 typos. script(0) should be $script(0)

Conclusion: Update file first.mrc and first.ptm

Note: This code will only fire if old versions of addons are found (with *.mrc extension)
As 4.22.6 only ships with the newer .ppa versions this code will not fire.

**Comment by ghost** [comment]
Roaming/mIRC/script/dcc.mrc 515:15 block On dccserver: Invalid DCC type parameter, must be one of the following: chat, send, or fserve.

`on *:DCCSERVER:Chat:if ($creq == ignore) hdel pnp chat.open. $+ $nick | else hadd pnp chat.open. $+ $nick $creq server`

Error: Invalid DCC type parameter, must be one of the following: chat, send, or fserve.

Conclusion: According to mIRC's help file `Chat` (with uppercase C) is a valid DCC type parameter. Haven't fired the code, but I believe the isue is with mSLDev.

**Comment by ghost** [comment]
Roaming/mIRC/script/rawdisp.mrc 1814:13 block Ctcp Event missing target and commands.
Roaming/mIRC/script/rawdisp.mrc 1815:11 block Ctcp Event missing target and commands.
Roaming/mIRC/script/rawdisp.mrc 1816:13 block Ctcp Event missing target and commands.
Roaming/mIRC/script/rawdisp.mrc 1817:13 block Ctcp Event missing target and commands.
Roaming/mIRC/script/rawdisp.mrc 1824:10 block Ctcp Event missing target and commands.

```
ctcp *:SOUND:return
ctcp *:MP3:return
ctcp *:SLOTS:return
ctcp &175:DO:{
  if ($_cfgi(doaccess)) {
    $2-
    set -u %.ctcp.reply 0
  }
  _do.rctcp $1-
}
ctcp &*:*:_do.rctcp $1-
```

Error: Missing target. ctcp events have three colons (:)

Conclusion: Bugfixes required in 5 lines in rawdisp.mrc and rawdisp.ptm

**Comment by craze** [comment]
CTCP events without a target specified works as if sent directly to user. Although undocumented as far as I can tell, it's not dysfunctional as is right now.

**Comment by solbu** [comment]
My opinion is that we should not use undocumented mIRC features, unless something breaks and using the undocumented feature is the only fix.

**Comment by madslyng** [comment]
I can only agree with @solbu - using undocumented features can lead to problems with forwards compatibility (the undocumented "feature" can be fixed), and it also makes it less understandable for people relying on the documented features.
