### ISSUE TITLE
/config 24 - Removing a channel in Config > Options > Channel options

### ISSUE THREAD

**Issue by ghost** [solbu/Peace-and-Protection#15]
When removing a channel in Config > Options > Channel options, the channel is removed from the list box, however upon clicking OK on the page to confirm and upon returning to Channel options, the channel is still listed.

Cause: the associated hash item (chopt.#channelname) in hash table pnp.config is not removed.

**Comment by ghost** [comment]
Tested on mIRC 6.01 + PnP 4.22 and mIRC 6.01 + PnP 4.21 (both have the bug present)

**Comment by ghost** [comment]
Method 1:

Delete config for all channels by inserting (Line 1365 - config.mrc:)
`hdel -w pnp.config chopt.*`
Let the original code re-save all config.

Method 2:
Run through all channels stored in hashes by using $hfind(pnp.config,chopt.*,0,w) and only hdel the one that isn't listed in $did(453).lines

**Comment by ghost** [comment]
Method 2:

[Link to pastebin.com](http://pastebin.com/eebERNt5)

Method 2b:

[Link to pastebin.com](http://pastebin.com/xAMjYtrV)

**Comment by ghost** [comment]
hm method 1 is no longer a good workaround... hdel -w pnp.config chopt.\* is not the same as running set chopt.#channel  
set chopt.#channel also runs a write -ds and broadcastp command:

```
; `set varname [value]
; varname should not include the %`
; If we ever change this, search for cfgvar.dat as certain routines use it
`set {
  if ($hget(pnp.config,$1) == $2-) return
  if ($2- == $null) {
    hdel pnp.config $1
    write -ds [ $+ [ $1 ] ] config\ $+ $hget(pnp,user) $+ \cfgvar.dat
    _broadcastp hdel pnp.config $1
  }
  else {
    hadd pnp.config $1 $2-
    write -s [ $+ [ $1 ] ] config\ $+ $hget(pnp,user) $+ \cfgvar.dat $1-
    _broadcastp _`set $1
  }
}
```

**Comment by ghost** [comment]
On line 1363 - 1373 config.mrc implement method 2b:

Before:

```
; Channel options
  :24
  var %ln = $did(453).lines
  while (%ln) {
    var %chan = $did(453,%ln)
    if ($left(%chan,1) == $chr(40)) %chan = chopt
    else %chan = chopt. $+ %chan
    `set %chan $did(454,%ln)
    dec %ln
  }
```

After:

```
; Channel options
  :24
  var %ln = $did(453).lines
  while (%ln) {
    var %chan = $did(453,%ln)
    if ($left(%chan,1) == $chr(40)) %chan = chopt
    else %chan = chopt. $+ %chan
    `set %chan $did(454,%ln)
    dec %ln
  }
  ; deleting channel(s)
  var %chanlist = $didtok($dname,453,44),%num = $hfind(pnp.config,chopt.*,0,w)
  while (%num > 0) {
    var %chan2 = $right($hfind(pnp.config,chopt.*,%num,w),-6)
    if (!$istok(%chanlist,%chan2,44)) { `set $hfind(pnp.config,chopt.*,%num,w) }
    dec %num
  }
  return
```

**Comment by acvxqs** [comment]
I think you're right about the _okcancel line of code @craze. It shouldn't be there, because if a user clicks OK in the _okcancel dialog to indicate that they wish to remove that channel, and then clicks Cancel in the main /config dialog, the channel is not removed. If you're happy with the ; deleting channel(s) code block, we can action that whenever you're ready... :sweat_smile:
