### ISSUE TITLE
Error during 'Verifying script order'

### ISSUE THREAD

**Issue by mdhoney** [solbu/Peace-and-Protection#17]
mIRC 7.44 and PnP 4.22.6 gives this on startup:

```
*** Performing PnP startup... (profile - default)
*** Error during 'Verifying script order'
*** Addons loaded- ChanServ NickServ Extras Sound
*** Startup completed in 1.217 seconds
```

**Comment by ghost** [comment]
The order in which the remote scripts are loaded is important. (first.mrc should be first, last.mrc should be last). If you change the order of the PnP scripts, PnP will detect it and then attempt to solve this. The next time you start PnP, you shouldn't see any errors.

Example of this issue (can be reproduced by changing the order of first.mrc):
![image](https://cloud.githubusercontent.com/assets/13683523/17025003/42d027ca-4f5a-11e6-802e-d4fe84164cc1.png)
Simply click OK, File > Save&Exit. Exit mIRC and restart...

**Comment by mdhoney** [comment]
Hmm, I couldn't for the life of me bring up that menu you show - where is it hiding?
But I will say this; mIRC shows this error message _every_ time for me, so it seems there is definitely no "optimizing" gong on,

**Comment by ghost** [comment]
The order of scripts can be changed by going in to the Scripts Editor (Alt + R) and then select File > Order. It's unusual that a clean installation of PnP keeps reporting an error during verifying script order.
I've performed a clean install and checked the order:

![image](https://cloud.githubusercontent.com/assets/13683523/17051211/b52da836-4ff7-11e6-9e51-dfa5936520ff.png)

`//var %x 1 | while ($nopath($script(%x))) { echo -ag $ifmatch | inc %x }`

Please compare it to your output and perhaps note any differences?
Do you get any other error messages?

P.S.: Have you upgraded to mIRC 7.45 yet? 7.44 had a bug whereby the on BAN/UNBAN event wouldn't fire.

**Comment by mdhoney** [comment]
Thanks for your response!  With your help I managed to locate the problem.  Another script, [sbClient](http://dukelupus.com/sbclient), was what was causing the problem.  I tried changing the order so that _sbClient.mrc_ would load after _last.mrc_, but couldn't get the change to stick.  Once I unloaded sbClient I stopped getting the error message.

**Comment by ghost** [comment]
PnP has an internal timer running and one of the things it does is checking whether last.mrc is the last script loaded. If this isn't the case, it reloads script\rawdisp.mrc and script\last.mrc at the tail end. Try to position sbClient before rawdisp.mrc, maybe that works!

```
_tut.on .timer.internal -io 0 10 _internal.timer | .timer.titleupd -io 0 1 _upd.title
_internal.timer {
  _aa.chk
  if (*last.mrc !iswm $script($script(0))) _screload
}
_screload {
  ; Skip reload if files don't exist
  if ($exists(script\rawdisp.mrc) == $false) halt
  if ($exists(script\last.mrc) == $false) halt
disps Script load detected $+ $chr(44) reordering PnP scripts
  .reload -rs $+ $calc($script(0) + 1) "script\rawdisp.mrc"
  .reload -rs $+ $calc($script(0) + 1) "script\last.mrc"
}
```
