### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by fahadmehar** [solbu/Peace-and-Protection#26]
Hello,  I download latest ver of PnP  and I try to load in Latest ver of mIRC v7.46 but it doesn't seems to be working... Please fix this.   Thanks

**Comment by ghost** [comment]
Have you followed the instructions here?

https://github.com/solbu/Peace-and-Protection/wiki/Installing%20PnP

**Comment by fahadmehar** [comment]
I Turn off conform, I follow the instructions but 

* /load: no such file 'C:\Users\MULTI\AppData\Roaming\mIRC\script\first.mrc'

**Comment by ghost** [comment]
That error message simply means script\first.mrc isn't located under %appdata% if you performed the command /load -rs script\first.mrc. 

Check whether the folders and files are correctly extracted to %appdata%

**Comment by fahadmehar** [comment]
No sir its not working... Its only working with OLD Versions... I Extract files on septate folder and put in D Drive and then I try to run.

**Comment by fahadmehar** [comment]
* Loaded script 'C:\Users\MULTI\Desktop\Peace-and-Protection-4.22.6\script\first.mrc'
-
Peace and Protection requires mIRC 7.43 or later to run! (you are using 6.17)

If I put 7.43 it will work but not with v7.46

**Comment by fahadmehar** [comment]
It is connected... I can't able to open ...Setting....Protection...I get this....
Settings are not working...

PROTEDIT Unknown command" 

ETOPIC Unknown command
-
AWAYCFG Unknown command

STRICT Unknown command

**Comment by fahadmehar** [comment]
I download script from here,,, and in your website there is an ver Version 4.22.6 is released. (2015-08-27)

Which one is latest? I downloaded this on Aug 27, 2015 
v4.22.6  …
 d5a25d7   zip   tar.gz

**Comment by fahadmehar** [comment]
And also please tell me when i join any channel i see topics in blue color and CTCP Ver on main,, How I disable that ?

**Comment by ghost** [comment]
The latest release is 4.22.6. 

Topics in blue? That's configurable.Its part of the theme you are using. I believe you can change it under Theme Central > Edit theme > Pnp colors > Target color.  

Not sure what you mean by ctcp ver on main. Have you got a screen Pic?

**Comment by fahadmehar** [comment]
I want on/join topic normal as we see in normal mIRC and  Problem is when I join channel after topic i see 
 [01#chatworld] topic- set by 01Fahad!~Fahad@119.154.102.117 (12Wed 5th Oct 2016 07:49p)
010212 [01#chatworld] users- 0114 total user(s)
010212 [01#chatworld] users- 011 op(s) 017.14% - 017 voice(s) 0150% - 016 other(s) 0142.86%
010212 01········02········12········14········15········
010212 [01#chatworld] url- 12https://www.dalnetchatworld.doodlekit.com/

I want to remove and use like normal mIRC....

3rd Problem is.... When we see someone CTCP Version... I see Replay on main channel i want to see on Status Window.

**Comment by ghost** [comment]
I'm not sure what you mean with "I want to remove and use like normal mIRC?" If you desire to remove PnP, then you should 1] Quit mIRC if it's running 2] delete everything under %appdata% (except for logs if you wish to keep it 3] start mIRC

3rd problem ctcp in active, want to see in status window:
You can control (turn on/off) that setting in PnP Options > Display > Other as seen here:
![image](https://cloud.githubusercontent.com/assets/13683523/19418761/09513038-93cb-11e6-86e8-0bdcf94e8d79.png)

**Comment by ghost** [comment]
Closing issue, hope this has all helped. If not just reopen or submit new ticket. Cheers!
