### ISSUE TITLE
Tab spaces (position) in custom windows

### ISSUE THREAD

**Issue by ghost** [solbu/Peace-and-Protection#29]
I propose the following changes to tab spaces in the following files:
### banlist.mrc
Line 20 - from:
```
_window 2.6 -nhlvk -t3,30,39,50 %win -1 -1 -1 -1 @banlist
```
to:
```
_window 2.6 -nhlvk -t3,120,160,200 %win -1 -1 -1 -1 @banlist
```
Line 254 - from:
```
else _window 2.7 -slzk -t10,25,40 @Blacklist $_winpos(8,12,10,10) @Blacklist
```
to:
```
else _window 2.7 -slzk -t40,120,160 @Blacklist $_winpos(8,12,10,10) @Blacklist
```

### dcc.mrc
Line 128 - from:
```
else _window 2.7 -lizk -t30 @DCClist $_winpos(8,12,10,10) @DCClist
```
to:
```
else _window 2.7 -lizk -t120 @DCClist $_winpos(8,12,10,10) @DCClist
```
Line 225 - from:
```
_window 2.3 -lnzk $+ $iif($_cfgi(dccqueuehide),h) -t15 @DCCQueue -1 -1 -1 -1 @DCCQueue
```
to:
```
_window 2.3 -lnzk $+ $iif($_cfgi(dccqueuehide),h) -t40 @DCCQueue -1 -1 -1 -1 @DCCQueue
```

### info.mrc
Line 18 - from:
```
_window 2. -hlnv -t13,24 @Clones -1 -1 -1 -1 @Clones
```
to:
```
_window 2. -hlnv -t40,80 @Clones -1 -1 -1 -1 @Clones
``` 
Line 280 - from:
```
_window 2.6 -lv -t25,30,35,40 @ServerDetails -1 -1 -1 -1 @ServerDetails
```
to:
```
_window 2.6 -lv -t40,80,120,160 @ServerDetails -1 -1 -1 -1 @ServerDetails
```
Line 437 - from:
```
else _window 2.6 -lkv -t16,22+l %win $_center(350,350) @Ports
```
to:
```
else _window 2.6 -lkv -t40,80+l %win $_center(350,350) @Ports
```

### userlist.mrc
Line 251 - from:
```
else _window 2.6 -slzk -t10,35,40,50 @Userlist $_winpos(8,12,10,10) @Userlist
```
to:
```
else _window 2.6 -slzk -t40,120,160,200 @Userlist $_winpos(8,12,10,10) @Userlist
```

### Summary:
banlist.mrc - L20 -t3,120,160,200 (banlist)
banlist.mrc - L254 -t40,120,160 (Blacklist)

dcc.mrc - L128 -t120 (DCClist)
dcc.mrc - L225 -t40 (DCCQueue)

info.mrc - L18 -t40,80 (Clones)
info.mrc - L280 -t40,80,120,160 (Serverdetails)
info.mrc - L437 -t40,80 (Ports)

userlist.mrc - L251 -t40,120,160,200 (Userlist)

### Conclusion:
Looks much better, also still fits nicely on a 1024x768 resolution screen.

What do you reckon @solbu and @craze?

**Comment by ghost** [comment]
Take for example the userlist window.

Before:
![image](https://cloud.githubusercontent.com/assets/13683523/25663665/95b14b78-3018-11e7-943b-5d8553190fa4.png)
After:
![image](https://cloud.githubusercontent.com/assets/13683523/25663592/642984da-3018-11e7-84e0-e7ccd262813e.png)

**Comment by ghost** [comment]
Second round of changes:

### Summary:
banlist.mrc - L20 -t3,68,78,88 (banlist)
banlist.mrc - L254 -t20,85,125 (Blacklist)

dcc.mrc - L128 -t65 (DCClist)
dcc.mrc - L225 -t20 (DCCQueue)

info.mrc - L18 -t20,35 (Clones)
info.mrc - L280 -t25,30,35,40 (Serverdetails)
info.mrc - L437 -t20,35 (Ports)

userlist.mrc - L251 -t20,85,91,106 (Userlist)

**Comment by solbu** [comment]
Somehow I overlooked this one.

The changes looks fine to me. Feel free to commit them.
