### ISSUE TITLE
HOTLINK

### ISSUE THREAD

**Issue by WildClaudio** [solbu/Peace-and-Protection#35]
OS: Win 7(x64) mIRC: 7.51 Pnp:4.22.7

Hello i`v just updated mIRC/PnP and since then HOTLINK doesnt work anymore, hotlink beeing web links/#channels are not double clickable anymore i`v tried to search in mIRC`s option and PnP nothing solved the problem maybe its something that has to do with the new FIX from mIRC version 7.51.thank you in advance.

as a test, i`v just downgraded mIRC version back to 7.49 and now  HOTLINK works. mIRC 7.51 without PnP also works great.

**Comment by ghost** [comment]
Is this what you are experiencing? https://forums.mirc.com/ubbthreads.php/topics/261662/Re:_Clicking_on_a_URL_link_in_#Post261662

**Comment by WildClaudio** [comment]
not really, i mean when you whois someone you`ll get channel list so if you want to join a channel you`ll simply double-click on it(#channel_name) mouse cursor will change in "hand-finger" seeing it as HOTLINK,. that stopped to work with 7.51. www.google.com and #channel are not  double-clickable in channel/private messages

**Comment by ghost** [comment]
Ok, I can only test this via wine on a Mac at the moment, but I can verify that on macOS + wine + mIRC 7.51 + pnp 4.22.7 double-clicking and right-clicking channel names in a whois window works.

@WildClaudio Do you have other non-pnp scripts running?
Can anyone else verify this issue?

**Comment by ghost** [comment]
By any chance, have you got 'Shift key enables hotlinks' enabled?
See alt + o > other > keys
<img width="224" alt="schermafbeelding 2017-11-13 om 18 51 17" src="https://user-images.githubusercontent.com/13683523/32740722-1d194092-c8a4-11e7-9f29-e03bd737c635.png">

edit: Feel free to join us on #peace&protection on EFNet...

**Comment by WildClaudio** [comment]
no, i dont have it, i am using PnP and mIRC since i know myself, the issue is only with 7.51 i dont run any scripts as i`v disabled them*had a winamp one actually a simple alias*. checked double checked  before writing here. well as told already i`v downgraded my mIRC version back to 7.49, as 7.51 has a HOTLINK FIX that seams to be a bug running it with PnP

**Comment by WildClaudio** [comment]
mirc 7.49 -[url=https://postimg.org/image/kgxbkk3x5/][img]https://s20.postimg.org/kgxbkk3x5/HCB.jpg[/img][/url] [url=https://postimg.org/image/blwha1uk9/][img]https://s20.postimg.org/blwha1uk9/HCWB.jpg[/img][/url] [url=https://postimg.org/image/6n8yvij1l/][img]https://s20.postimg.org/6n8yvij1l/HWB.jpg[/img][/url]

**Comment by WildClaudio** [comment]
mIRC 7.49

![hcb](https://user-images.githubusercontent.com/8040906/32744089-5d0aa34c-c8a6-11e7-9bbe-2d85fe2acf8c.jpg)
![hcwb](https://user-images.githubusercontent.com/8040906/32744092-6097aab4-c8a6-11e7-9cf2-8146a01b29d8.jpg)
![hwb](https://user-images.githubusercontent.com/8040906/32744094-6506f29e-c8a6-11e7-8821-f56e2fbc6928.jpg)

mIRC 7.51

![hww](https://user-images.githubusercontent.com/8040906/32744113-77ea2908-c8a6-11e7-883c-e652b64093bb.jpg)
![hcw](https://user-images.githubusercontent.com/8040906/32744114-781c6774-c8a6-11e7-9a27-4012ef629ef1.jpg)
![hcww](https://user-images.githubusercontent.com/8040906/32744115-7843d994-c8a6-11e7-8804-d20c343c29c2.jpg)

**Comment by WildClaudio** [comment]
OK, I have been able to see WHY HOTLINK wont work. The issue seams to be related to mIRC update.
Quick FIX: delete mirc.exe from your mIRC folder before updating but still if you want to keep all .ini files intact chose just upgrade when asked in mIRC installation STEPS. normaly mIRC update will overwrite mirc.exe on a upgrade but it seams that HOTLINK wont work anymore if you already have PnP loaded on the "older" version.thank you in advance

**Comment by ghost** [comment]
Ok I'll close the issue. Thanks for looking into this for us :)
