### ISSUE TITLE
first,mrc missing from script folder

### ISSUE THREAD

**Issue by Roughd1433** [solbu/Peace-and-Protection#36]
When doing a fresh install using the latest version when you run the /load script command you get an error saying first.mc is missing.

**Comment by craze** [comment]
From mIRC v6.3 and onward, PnP should be extracted to the folder that opens with `//run $mircdir`.
With default installation settings, this is `%APPDATA%\mIRC` in Windows. 

For traditional behaviour with everything in one place instead, you can try copying `mirc.ini` from this location to where you actually installed mIRC.
