### ISSUE TITLE
Cannot load on mirc 7.52

### ISSUE THREAD

**Issue by mrfanatic** [solbu/Peace-and-Protection#37]
I got this error when i do `/load -rs script\first.mrc`

```
* Loaded script 'C:\Users\Ryzen\AppData\Roaming\mIRC\script\first.mrc'
* No such identifier: $_cfgi (line 825, first.mrc)
```

PnP version: v4.22.8

**Comment by ghost** [comment]
In the script editor under Options, you most likely have `Identifier Warning` enabled. Disable this check.

**Comment by mrfanatic** [comment]
Thanks, after disabling both warning i can load on 7.52 now 👍
https://prnt.sc/ldvmqx
