### ISSUE TITLE
on changing lang

### ISSUE THREAD

**Issue by burakataoglu** [solbu/Peace-and-Protection#38]
I've got error on translations. 

stuck at 48%

english -> turkish

Invalid format: $evalnext (line 166, translate.mrc)

pnp v. 4.22.8
mirc v. 7.54

**Comment by ghost** [comment]
The bad news is that I can reproduce this with mIRC 7.54 and PnP 4.22.8

The good news is that everything works in mIRC 7.57 and PnP 4.22.8 (Well, not everything. When installing PnP on 7.57 it doesn't auto-restart when running /load -rs script\first.mrc)

Also, keep in mind that PnP is nearly 20 years old! (PnP was build on mIRC 6.01)

Unfortunately there's not much we can do. Apart from reporting it to Khaled on the mirc forum.

**Comment by burakataoglu** [comment]
:) thanks for answer.

no problem.
