### ISSUE TITLE
Problem with users- count > 100%

### ISSUE THREAD

**Issue by ghost** [solbu/Peace-and-Protection#43]
**Describe the bug**

- Everyone is counted as an op one more time than supposed to. Ops are counted twice, while everyone else is counted as ops once (too).
- Anyone with more than one mode (op/halfop/voice) is counted equally many times. (For example both as op and voice)
- Being alone with +ohv in a channel will return 1 total user(s), 2 ops, 1 halfop, 1 voice to a /names request.

```
*** [#underworld] topic- set by X (Thu 8th Jan 2009 05:18p)
*** [#underworld] users- 37 total user(s)
*** [#underworld] users- 39 op(s) 105.41% - 35 other(s) 94.59%
```

**Please complete the following information:**
 - mIRC version: 7.61
 - PnP version: 4.22.9

**Additional context**

Short answer
Scratching the surface of this, it appears that PnP can't handle UHNAMES messages from server properly.

Long answer
UHNAMES is different as the whole nick!user@host is returned in addition to every mode (@%+) the user has on channel instead of just a nickname with the first matching prefix.

PnP seem to count every occurrence of defined prefixes when it receives a NAMES reply from server. This includes every usermodes set, plus the @ between ident and ip/host will increase the op count as well. With traditional NAMES responses, this hasn't been an issue.

It's not as much a bug as it is something PnP just wasn't designed to do. Nevertheless, it is still a problem that can - and should be - addressed with a script fix. With PnP no longer in active development, such fixes depends on being submitted by the community.

**Comment by ghost** [comment]
**Solution**

Find the following in rawdisp.mrc on line 803
```
hinc pnp. $+ $cid -namec. $+ $mid($prefix,%num,1) $count($4-,$mid($prefix,%num,1))
```
and replace with:
```
hinc pnp. $+ $cid -namec. $+ $mid($prefix,%num,1) $count($+($chr(32),$4-),$+($chr(32),$mid($prefix,%num,1)))
```

**Comment by RyanBlakeIT** [comment]
Modified file as directed by acvxqs and it gives this error message:

Server does not recognize 	HINC command

Also the count of ops, etc, is now blank.  Just says: users

**Comment by RyanBlakeIT** [comment]
This worked but also had to change line 461 and add brackets else I was getting an error saying Server does not recognize HINC

`    if (%status) { hinc pnp. $+ $cid -dwho. $+ %status }`

**Comment by ghost** [comment]
I'll just ask you about this @craze as you are the original poster on the forums regarding this.
Thanks for the feedback @RyanBlakeIT !
