### ISSUE TITLE
'Sample message' in Pnp Options > Messages is not showing

### ISSUE THREAD

**Issue by kh262** [solbu/Peace-and-Protection#46]
Hello, 
Please see the attached file it will explain it all, appreciate your help and feedback 

Regards 

**Please complete the following information:**

![pnp](https://user-images.githubusercontent.com/24794114/78411643-62189d00-7621-11ea-9976-694b5830c889.JPG)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - mIRC version:  7.61
 - PnP version: 4.22.9

**Additional context**

**Comment by ghost** [comment]
**Additional information:**
PnP remembers what section you last viewed in the Options dialog. When opening up Options, it will focus (automatically go to) on this section.
This particular problem is only happening when you open the Options dialog and 'Messages' is NOT the last viewed section. When you then navigate to 'Messages'in the left hand listbox, it bugs.

However, if you are in the 'Messages' section and click OK and exit out of the dialog and then open the options dialog again, it then shows the sample correctly...

**Comment by kh262** [comment]
Thanks :) it works now

**Comment by ghost** [comment]
@kh262 The sample preview for messages may work when closing and reopening the PnP options dialog, however it still remains an issue, hence I'm reopening...

**Comment by solbu** [comment]
Could it be linked to issue #52?

**Comment by ghost** [comment]
> Could it be linked to issue #52?

I don't think so, for PnP was working fine with `option dbu` for all these years. I've just revisited this issue in mIRC 7.67 and PnP 4.22.9 and the issue has gone! Can you verify and confirm it is working properly now @kh262 ? (And perhaps @craze can give this his thumbs up too?)

**Comment by ghost** [comment]
This issue seems to have resolved itself with mIRC version 7.68 ...
