### ISSUE TITLE
Disable /who on connect

### ISSUE THREAD

**Issue by noipstream** [solbu/Peace-and-Protection#48]
Not able to disable /who on connect and bouncer gets disconnected by server due to excess flood.

**Comment by ghost** [comment]
1. There's no such thing as a /who on connect;
2. There is who-on-me-join defined in 110-118 script.mrc:
```
; Temp - May expand/replace later
on me:^*:JOIN:#:{
  ; (highlight on join)
  window -g1 " $+ $chan $+ "
  repjoin -r $chan
  if ($ial) if ($chan($chan).inwho == $false) _linedance _who.queue $chan hide
  if ($_cfgi(fill.chan)) _recent chan $_cfgi(num.chan) 0 $chan
  _recseen 10 chan $chan
}
```
The _who.queue alias as well as code that processes the WHO return values are found in rawdisp.mrc line 405 onwards:
```
; /_who.queue channel command/hide
; Queues a 'who'; Make sure you are queing a single channel (no nicks, no wildcards, etc)
alias _who.queue {
  hadd -m pnp.qwho $cid $+ . $+ $1 $2-
  .raw who $1
}
```
3. This behaviour is not really a bug in PnP as this is just how PnP was designed. (To run a /who $chan on me-join). (Please mind, PnP is nearly 20 years old and afaik wasn't designed with bouncers in mind.)
4. So when connecting to a bouncer, from mIRC's perspective you are joining _N_ channels on the particular server you are connected to and therefore launching _N_ times /who... thereby flooding you (bouncer) off the server...
5. Also, different irc servers, different levels of sendq (Inspircd = [1M](https://github.com/inspircd/inspircd/blob/b7382a91384e6e9463ba85c6effec32f071dd4ca/docs/conf/inspircd.conf.example#L408), unreal = [200KB](https://github.com/unrealircd/unrealircd/blob/ead0ad0aa69016e04fc4f4959ca2efabb3cad2c1/doc/conf/examples/example.conf#L88) )
6. Perhaps an ON PARSELINE:OUT event can capture the /who command and block it/delay it

**Comment by ghost** [comment]
Ah I see you have closed the issue, but I had only jotted down a few notes/thoughts.
Our mission statement does not allow us to alter pai's code in any way, but we can always add a new script and see if we can workaround this particular behaviour you mentioned.

This piece of code will intercept a `/who $chan` and delay it by 2 seconds, which ought to be enough time to process earlier who replies...
In the script editor > File > New...
```
on *:PARSELINE:out:WHO &:{
  var %pl $parseline, %t $ticks + 2000
  ;echo 4 -sg Intercepting: %pl
  while (%t >= $ticks) noop
  if ($parseutf) %pl = $utfencode(%pl)
  .parseline -otu0 %pl
  return
}
```
Edit: Please let us know if this works for you.

**Comment by ghost** [comment]
I had a chat with support in ##znc on freenode, discussing this problem and asking them about what could be done on a bouncer's end. Basically there's many clients who make plenty of /who calls (Textual does so every 2 minutes; mirc + pnp only once upon joining a channel)
So if you're using znc as a bouncer have a look in the network > edit section.

![image](https://user-images.githubusercontent.com/13683523/80279718-9dc5f480-86ff-11ea-9710-c74ce7ad0dd7.png)

Flood protection is definitely recommended and ought to be enabled with the above values as defaults.
Also you can try fiddle with the channel join delay. In all, all these things will defend against flooding yourself off the network.

However, there's little to no detailed information about the problem so there isn't much else I can do to help.
