### ISSUE TITLE
Server does not recognize _UPD.TITLE command

### ISSUE THREAD

**Issue by procdaddy11** [solbu/Peace-and-Protection#51]
Using latest pnp and mirc. I've tried reloading and issue stops if I unload pnp.

The bellow error spams constantly making mirc unusable

*** Server does not recognize _UPD.TITLE command
*** Server does not recognize _UPD.TITLE command

**Comment by ghost** [comment]
https://github.com/peace-and-protection/Peace-and-Protection/blob/1746c74d8133c1b2574032c498617c702dd1a4bd/script/alias1.mrc#L557-L571

`_upd.title` is an alias in file alias1.mrc, so I must ask if you have that alias file loaded at all?
The alias is responsible for updating the titlebar information in the main mIRC window.

`_upd.title` gets called, for example, every $_cfgi(sptime) seconds if lag checking is turned on...(by default this is every 30 seconds)

Maybe an error happened upon installing PnP. So I must ask, how did you install pnp? Did you follow the steps as outlined [here](https://github.com/peace-and-protection/Peace-and-Protection/wiki/Installation)?

**Comment by procdaddy11** [comment]
Weirdest thing. I closed out of mIRC when this was happening and have't opened it since. But opened it today to follow-up on this and everything is fine.
