### ISSUE TITLE
Anti-idle feature not working when PRIVMSG is upgraded by mIRC to CPRIVMSG (Undernet for example)

### ISSUE THREAD

**Issue by ghost** [solbu/Peace-and-Protection#54]
**Describe the bug**
Anti idle feature in add-on EXTRAS.PPA does not function when in channel on Undernet.

**To Reproduce**
1. Connect to Undernet and join an empty channel (you are opped)
`/server -m irc.undernet.org -i testaccount testaccount_ -j #testabcd1234`
2. Install extras.ppa
`/addon i addons\extras.ppa`
3. Enable antiidle:
`/aidle on`
4. Ext Whois yourself:
`//ew $me`

Wait a few minutes and ext whois yourself again. The idle counter for your nick on the server does NOT reset to 0.

**Expected behavior**
Idle counter to be reset to 0 upon ext whois yourself.

**Please complete the following information:**
 - mIRC version: 7.68
 - PnP version: 4.22.9

**Additional context**

First reported by user snow on the kristshell pnp forum.
The command used in PnP is: `scid -at1 .msg $!me antiidle`
The `/msg` command used in PnP (silent with . prefix) results in a CPRIVMSG from the server and no reset on idle counter.

Behaviour arround mIRC and upgrading PRIVMSG to CPRIVMSG command is described here: https://en.wikichip.org/wiki/mirc/behaviors#CPRIVMSG_.2F_CNOTICE

**Comment by ghost** [comment]
To resolve this issue change:
https://github.com/peace-and-protection/Peace-and-Protection/blob/1746c74d8133c1b2574032c498617c702dd1a4bd/addons/EXTRAS.PPA#L185
to
` scid -at1 raw -q PRIVMSG $!me antiidle`

**Comment by cnecrea** [comment]
Many thanks for this fix!

Regards,
snow.

**Comment by ghost** [comment]
I just came across something else that is related. So I leave this note here:

The proper syntax is actually a little different as seen on this line:

https://github.com/peace-and-protection/Peace-and-Protection/blob/362a61f5dab426787af0c7af06333c7d208be10b/script/ctcp.mrc#L612

So I believe my fix is better written as:

``scid -at1 _privmsg $!me antiidle``

Note: I'm not sure about ``$!me`` in here and I've no windows computer atm to test. (double-evaluation)
