### ISSUE TITLE
* Loaded script 'C:\mIRC\script\first.mrc', * /hmake: hash table exists 'pnp.1' (line 821, first.mrc)

### ISSUE THREAD

**Issue by littlAcen** [solbu/Peace-and-Protection#55]
* Loaded script 'C:\mIRC\script\first.mrc'
-
* /hmake: hash table exists 'pnp.1' (line 821, first.mrc)

how to fix this? :)

**Comment by ghost** [comment]
# Short answer

I would follow the installation guide as posted over at the wiki[^1].

## Exception

If you cannot or don't want to install PnP in `"%appdata%\mIRC"`[^2], install pnp422 in `"%appdata%\pnp"`, make sure you create an application shortcut with the -r switch, e.g.: **Target:** `C:\Program Files (x86)\mIRC\mIRC.exe -r"%appdata%\pnp"` and start that instance of mIRC.exe with it by double-clicking the shortcut and launching it.

# Long answer

I'd like to dissuade you from putting mIRC's core files and user data files in the one location. (Everything in C:\mIRC\)

In a perfect setup, you only need to install mIRC (its core files) once. Typically this will be in `C:\Program Files (x86)\mIRC`.
You can then install (full mirc) scripts in different user data locations. For example: `"%appdata%\fullscript1"` and `"%appdata%\fullscript2"`
The trick is then to create an application shortcut (right-click your Desktop and select New -> Application Shortcut) and specify the target: `[DRIVE:]\[MIRCLOCATION]\[MIRC.EXE] -r"[USERDATALOCATION]"`. You can see an example for the nbs-irc script here: https://github.com/ElectronicWar/nbs-irc/issues/9#issue-171015174

Good luck and let us know how you're going!

[^1]: [https://github.com/peace-and-protection/Peace-and-Protection/wiki/Installation](https://github.com/peace-and-protection/Peace-and-Protection/wiki/Installation)
[^2]: `"%appdata%\mIRC"` is the default location for user data files for mIRC. You can type `%appdata%` in the Windows Explorer address bar and hit _Enter_ to go there quickly.
